# Standalone file: do not edit by hand
# Generated by: pkgtools from @unit tags
# ----------------------------------------------------------------------
library(jpansim2analysis)

# unit test start: .inputter ----

test_that(".inputter unit test", {
  # Automatically generated test case from roxygen @unit tag
  # Do not edit here - follow the link to the source file.
  # or navigate to topic with <F2>
  F2 = .inputter

  inp <- .inputter(tempdir())
  for (i in 1:10) {
    fs::file_touch(fs::path(tempdir(), sprintf("test_%d.txt", i)))
  }

  testthat::expect_true(fs::file_exists(inp("test_2.txt")))
  testthat::expect_error(inp("test_0.txt"))

  testthat::expect_equal(length(inp(glob = "*.txt")), 10)

  # generates a failure if the overall test is failing with a link to the
  # source of the unit test:
  testthat::expect(
    rlang::caller_env(n = 2)$ok,
    failure_message = "Source link for failing @unit test.",
    srcref = srcref(
      srcfile("../../R/import-standalone-directory-utils.R"),
      c(34, 1, 34 + 1, 1)
    )
  )
})

# unit test end: .inputter ----
# unit test start: .outputter ----

test_that(".outputter unit test", {
  # Automatically generated test case from roxygen @unit tag
  # Do not edit here - follow the link to the source file.
  # or navigate to topic with <F2>
  F2 = .outputter

  # default appends date to filename:
  out <- .outputter(tempdir())
  tmp <- out("test.pdf")
  testthat::expect_match(
    tmp,
    "^.*/test-[0-9]{4}-[0-9]{2}-[0-9]{2}.pdf$"
  )

  # default appends date to filename:
  out2 <- .outputter(tempdir(), datedSubdirectory = TRUE)
  tmp2 <- out2("test.pdf")
  testthat::expect_match(
    tmp2,
    "^.*/[0-9]{4}-[0-9]{2}-[0-9]{2}/test.pdf$"
  )

  # generates a failure if the overall test is failing with a link to the
  # source of the unit test:
  testthat::expect(
    rlang::caller_env(n = 2)$ok,
    failure_message = "Source link for failing @unit test.",
    srcref = srcref(
      srcfile("../../R/import-standalone-directory-utils.R"),
      c(87, 1, 87 + 1, 1)
    )
  )
})

# unit test end: .outputter ----
# unit test start: .locate_project ----

test_that(".locate_project unit test", {
  # Automatically generated test case from roxygen @unit tag
  # Do not edit here - follow the link to the source file.
  # or navigate to topic with <F2>
  F2 = .locate_project

  testthat::expect_no_error(withCallingHandlers(
    {
      .locate_project()
    },
    warning = function(e) {
      message("Warning issued: ", e$message)
      invokeRestart("muffleWarning")
    }
  ))

  # generates a failure if the overall test is failing with a link to the
  # source of the unit test:
  testthat::expect(
    rlang::caller_env(n = 2)$ok,
    failure_message = "Source link for failing @unit test.",
    srcref = srcref(
      srcfile("../../R/import-standalone-directory-utils.R"),
      c(148, 1, 148 + 1, 1)
    )
  )
})

# unit test end: .locate_project ----
# unit test start: .here ----

test_that(".here unit test", {
  # Automatically generated test case from roxygen @unit tag
  # Do not edit here - follow the link to the source file.
  # or navigate to topic with <F2>
  F2 = .here

  testthat::expect_no_error(withCallingHandlers(
    {
      .here("vignettes")
    },
    warning = function(e) {
      message("Warning issued: ", e$message)
      invokeRestart("muffleWarning")
    }
  ))

  # generates a failure if the overall test is failing with a link to the
  # source of the unit test:
  testthat::expect(
    rlang::caller_env(n = 2)$ok,
    failure_message = "Source link for failing @unit test.",
    srcref = srcref(
      srcfile("../../R/import-standalone-directory-utils.R"),
      c(232, 1, 232 + 1, 1)
    )
  )
})

# unit test end: .here ----
# end of unit tests ----
