---
title: "In host viral load model"
author: "Rob Challen"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
here::i_am("in-host-model.Rmd")
library(tidyverse)

# install.packages(
#   c("odin","odin.dust","dust"),
#   repos = c("https://mrc-ide.r-universe.dev", "https://cloud.r-project.org"))

```





# Stochastic biological model



```{r}

stoch1 = odin.dust::odin_dust({
  
  # Virions
  
  initial(virions) = 0
  update(virions) = virions + virions_added - virions_removed
  rate_virion_removal = user(1/0.2)
  rate_infection = user(1/0.2)
  rate_virion_replication = user(1/0.5)
  
  
  p_virion_removed_by_immunity = 1 - exp(- rate_virion_removal * immune_active / k_immune)
  p_virion_removed_by_infection = 1 - exp(- rate_infection * target_susceptible / k_target)
  
  p_virion_removal = 1 - (1-p_virion_removed_by_immunity)*(1-p_virion_removed_by_infection)
  
  virions_removed = rbinom(virions, p_virion_removal)
  virions_added = rpois(rate_virion_replication * target_producing)
  
  # Targets
  
  k_target = user(10000)
  
  initial(target_susceptible) = k_target
  initial(target_exposed) = 0
  initial(target_producing) = 0
  
  update(target_susceptible) = target_susceptible - target_infected + target_recovered
  update(target_exposed) = target_exposed + target_infected - target_start_producing
  update(target_producing) = target_producing + target_start_producing - target_producing_removed
  
  rate_target_recovery = user(1/30)
  rate_producing_given_exposed = user(1/3)
  rate_cellular_removal = user(1/0.2)
  
  p_infection_given_virion_removed = p_virion_removed_by_infection / p_virion_removal
  virions_infecting = rbinom(virions_removed, p_infection_given_virion_removed)
  # virions_infecting is a sample size and targets_susceptible is a pool size
  # coverage of the pool by repeated sampling with replacement is given by:
  # p_target_infected = 1-(1-1/target_susceptible)^virions_infecting
  target_interacted = virions_infecting * 1-(1-1/(1+virions_infecting))^target_susceptible
  
  p_target_infected = 1 - exp(- rate_infection * target_susceptible / k_target)
  target_infected = rbinom(target_interacted, p_target_infected)
  
  target_remaining = target_susceptible + target_exposed + target_producing
  target_removed = k_target - target_remaining
  
  
  p_target_recovery = 1-exp(-rate_target_recovery)
  target_recovered = rbinom(target_removed, p_target_recovery)
  
  p_producing_given_exposed = 1-exp(-rate_producing_given_exposed)
  target_start_producing = rbinom(target_exposed, p_producing_given_exposed)
  
  p_target_cellular_removal = 1-exp(- rate_cellular_removal * immune_active / k_immune)
  
  
  k_nk = user(1000)
  rate_nk_elimination = user(1/3)
  
  # k_nk the number of NK cells is a sample size and targets_producing is a pool size
  # coverage of the pool by repeated sampling with replacement is given by:
  p_nk_removal = 1-exp(-rate_nk_elimination * k_nk * target_producing / k_target)
  # p_target_nk_removed = p_nk_removal * 1-(1-1/target_producing)^k_nk
  
  p_target_producing_removed = 1-(1-p_target_cellular_removal)*(1-p_nk_removal)
  # p_target_producing_removed = 1-(1-p_target_cellular_removal)*(1-p_target_nk_removed)
  target_producing_removed = rbinom(target_producing, p_target_producing_removed)
  
  # Immunity
  
  k_immune = user(10000)
  initial(immune_priming) = 0
  initial(immune_active) = 0
  rate_induced_given_exposed = user(1/2)
  rate_active_given_induced = user(1/2) 
  rate_senescence_given_active = user(1/365)
  
  immune_dormant = k_immune - immune_priming - immune_active
  
  # immune_dormant = k_immune - immune_active
    
  p_induced_given_exposed = 1-exp(-rate_induced_given_exposed * (target_exposed+target_producing) / target_remaining)
  
  immune_induced = rbinom(immune_dormant, p_induced_given_exposed)
  
  p_active_given_induced = 1-exp(-rate_active_given_induced)
  immune_start_active = rbinom(immune_priming, p_active_given_induced)

  update(immune_priming) = immune_priming + immune_induced - immune_start_active
      
  p_senescence_given_active = 1-exp(-rate_senescence_given_active)
  immune_senescence = rbinom(immune_active, p_senescence_given_active)
    
  update(immune_active) = immune_active + immune_start_active - immune_senescence
  
  
  
}, skip_cache = TRUE)
```

```{r}


step = function(mod,i, infectFn = ~ if (.x %% 100 == 10) 100 else 0) {
  infectFn = rlang::as_function(infectFn)
  mod$run(i)
  
  s = mod$state()
  
  if (length(dim(s)) ==3) {
    s[1,,] = s[1,,] + infectFn(i)
    inf = mod$info()[[1]]
  } else {
    s[1,] = s[1,] + infectFn(i)
    inf = mod$info()
  }
  
  mod$update_state(state = s)
  n = names(inf$index)
  
  if (length(dim(s))==2) dim(s) = c(dim(s),1)
  
  bind_rows(lapply( 1:(dim(s)[3]) , \(set) {
    stmp = s[,,set]
    tibble::tibble(
      value = as.vector(stmp),
      boot = as.vector(col(stmp)),
      variable = n[as.vector(row(stmp))],
      step = i,
      set=set
    )
  }))
}

full_params = function(mod = stoch1$new(pars=list(), n_particles = 10,time=0)) {
  sweepDf = mod$pars() %>% purrr::list_transpose() %>% as.data.frame()
  defaults = mod$param() %>% purrr::map(~ .x %>% purrr::pluck("default_value"))
  defaults = defaults %>% map(\(x) {
      if (!is.list(x)) return(x)
      x[[1]] = as.name(x[[1]])
      return(x %>% as.call() %>% eval())
  }) %>% as_tibble()
  if (nrow(sweepDf) > 0) {
    return(sweepDf %>% cross_join(defaults %>% select(-any_of(colnames(sweepDf)))))
  } else {
    return(defaults)
  }
}

sweep = function(parsDf = tibble::tibble(boot=1), maxtime = 400,...) {
  if (!"set" %in% colnames(parsDf)) parsDf = parsDf %>% mutate(set = row_number())
  # pars = parsDf %>% purrr::transpose()
  pars = parsDf %>% as.list() %>% purrr::list_transpose(simplify = FALSE)
  
  mod <- stoch1$new(pars=pars, n_particles = 10,time=0,pars_multi = TRUE)
  step(mod,1)
  tmp = bind_rows(lapply(1:maxtime, \(i) step(mod,i,...)))
  full_params(mod) %>% inner_join(tmp, by="set")
}

plot_sweep = function(sweep, facets = ~variable) {
  
  tmp = tmp %>% 
    filter(variable %in% c("virions","target_susceptible","immune_active")) %>%
    group_by(across(-c(value,boot))) %>%
    summarise(value = mean(value))
  
  list(
  ggplot(tmp,aes(x=step-10,y=value,colour = as.factor(set),group=interaction(as.factor(set))))+
    geom_line()+guides(colour = guide_legend(override.aes = list(alpha=1)))+
    facet_wrap(facets,scales = "free_y"),
  ggplot(tmp,aes(x=step-10,y=value,colour = as.factor(set),group=interaction(as.factor(set))))+
    geom_line()+guides(colour = guide_legend(override.aes = list(alpha=1)))+
    facet_wrap(facets,scales = "free_y")+
    coord_cartesian(xlim=c(0,50))
  )
} 
```

```{r}


tmp = sweep(parsDf = tibble(
  rate_virion_replication = seq(1,10,1),
  rate_infection = 2/rate_virion_replication
))

tmp %>% plot_sweep()
```

# full_params() %>% as.list() %>% deparse() %>% clipr::write_clip()
# tibble(k_immune = 10000L, k_nk = 1000L, k_target = 10000L, rate_active_given_induced = 0.5, 
#     rate_cellular_removal = 5, rate_induced_given_exposed = 0.5, 
#     rate_infection = 5, rate_nk_elimination = 0.333333333333333, 
#     rate_producing_given_exposed = 0.333333333333333, rate_senescence_given_active = 0.00273972602739726, 
#     rate_target_recovery = 0.0333333333333333, rate_virion_removal = 5, 
#     rate_virion_replication = 2)

```{r}

tmp = sweep(parsDf = tibble(
  
  rate_virion_replication = 2, #c(1.5,2,2.5), #c(0.5,1,2,4), # c(0.5,1,2,4,8),
  # determines the time in which virions can be removed, smaller values affect virion removal very significantly.
  # short (i.e. larger) values lead to chronic infection as virus cannot be neutralised
  rate_infection = 1, #c(0.8, 0.9, 1, 1.1, 1.2), #c(3,2,1,0.5) # 1/rate_virion_replication * 2, #c(0.25,0.5,1,2,4,8), # * seq(1,2,0.1),
) %>% mutate(
  rate_producing_given_exposed = rate_infection,
  
  rate_virion_removal = rate_virion_replication * 1, #c(0.25,0.5,1,2,4),
  rate_cellular_removal = rate_virion_removal, # * c(0.25,0.5,1,2,4),
  
  rate_induced_given_exposed = 2, #c(1,2,3), #c(0.25,0.5,1,2,4,8), # severity roughly negatively linear with this.
  rate_active_given_induced = rate_induced_given_exposed, #* c(1,2,4,8), #c(0.5,1,2,4,8),
  
  rate_nk_elimination = 1, # c(0.25,0.5,1,2,4,8),
  k_nk = 0, # c(10,100,1000,10000)
  rate_senescence_given_active = 1/1000, #1/800,
  rate_target_recovery = 1/15 #1/c(15,30,60,180,360)
))

plts = tmp %>% plot_sweep(~variable)

plts[[1]]+guides(colour=guide_none())

```

https://math.stackexchange.com/questions/32800/probability-distribution-of-coverage-of-a-set-after-x-independently-randomly/32816#32816


```{r}

stoch = odin2::odin({
  
  # Virions
  
  initial(virions) = 100
  update(virions) = virions + virions_added - virions_removed
  rate_virion_removal = parameter(1/7)
  rate_infection = parameter(1/0.2)
  rate_virion_replication = parameter(1/0.5)
  
  
  p_virion_removed_by_immunity = 1 - exp(- rate_virion_removal * immune_active / k_immune)
  p_virion_removed_by_infection = 1 - exp(- rate_infection * target_susceptible / k_target)
  
  p_virion_removal = 1 - (1-p_virion_removed_by_immunity)*(1-p_virion_removed_by_infection)
  
  virions_removed = Binomial(virions, p_virion_removal)
  virions_added = Poisson(rate_virion_replication * target_producing)
  
  # Targets
  
  k_target = parameter(10000)
  
  initial(target_susceptible) = k_target
  initial(target_exposed) = 0
  initial(target_producing) = 0
  
  update(target_susceptible) = target_susceptible - target_infected + target_recovered
  update(target_exposed) = target_exposed + target_infected - target_start_producing
  update(target_producing) = target_producing + target_start_producing - target_producing_removed
  
  rate_target_recovery = parameter(1/30)
  rate_producing_given_exposed = parameter(1/3)
  rate_cellular_removal = parameter(1/0.2)
  
  p_infection_given_virion_removed = p_virion_removed_by_infection / p_virion_removal
  virions_infecting = Binomial(virions_removed, p_infection_given_virion_removed)
  # virions_infecting is a sample size and targets_susceptible is a pool size
  # coverage of the pool by repeated sampling with replacement is given by:
  # p_target_infected = 1-(1-1/target_susceptible)^virions_infecting
  target_interacted = virions_infecting * 1-(1-1/(1+virions_infecting))^target_susceptible
  
  p_target_infected = 1 - exp(- rate_infection * target_susceptible / k_target)
  target_infected = Binomial(target_interacted, p_target_infected)
  
  target_remaining = target_susceptible + target_exposed + target_producing
  target_removed = k_target - target_remaining
  
  
  p_target_recovery = 1-exp(-rate_target_recovery)
  target_recovered = Binomial(target_removed, p_target_recovery)
  
  p_producing_given_exposed = 1-exp(-rate_producing_given_exposed)
  target_start_producing = Binomial(target_exposed, p_producing_given_exposed)
  
  p_target_cellular_removal = 1-exp(- rate_cellular_removal * immune_active / k_immune)
  
  
  k_nk = parameter(1000)
  rate_nk_elimination = parameter(1/3)
  
  # k_nk the number of NK cells is a sample size and targets_producing is a pool size
  # coverage of the pool by repeated sampling with replacement is given by:
  p_nk_removal = 1-exp(-rate_nk_elimination * k_nk * target_producing / k_target)
  # p_target_nk_removed = p_nk_removal * 1-(1-1/target_producing)^k_nk
  
  p_target_producing_removed = 1-(1-p_target_cellular_removal)*(1-p_nk_removal)
  # p_target_producing_removed = 1-(1-p_target_cellular_removal)*(1-p_target_nk_removed)
  target_producing_removed = Binomial(target_producing, p_target_producing_removed)
  
  # Immunity
  
  k_immune = parameter(10000)
  initial(immune_priming) = 0
  initial(immune_active) = 0
  rate_induced_given_exposed = parameter(1/2)
  rate_active_given_induced = parameter(1/2) 
  rate_senescence_given_active = parameter(1/365)
  
  immune_dormant = k_immune - immune_priming - immune_active
  
  # immune_dormant = k_immune - immune_active
    
  p_induced_given_exposed = 1-exp(-rate_induced_given_exposed * target_producing / target_remaining)
  
  immune_induced = Binomial(immune_dormant, p_induced_given_exposed)
  
  p_active_given_induced = 1-exp(-rate_active_given_induced)
  immune_start_active = Binomial(immune_priming, p_active_given_induced)

  update(immune_priming) = immune_priming + immune_induced - immune_start_active
      
  p_senescence_given_active = 1-exp(-rate_senescence_given_active)
  immune_senescence = Binomial(immune_active, p_senescence_given_active)
    
  update(immune_active) = immune_active + immune_start_active - immune_senescence
  
  
  
}, skip_cache = TRUE)
```


```{r}

sys <- dust2::dust_system_create(stoch, pars = list(), n_particles = 10, dt=1)
dust2::dust_system_set_state_initial(sys)
time <- 0:400
plot <- dust2::dust_system_simulate(sys, time)

plot2 = dust2::dust_unpack_state(sys, plot)

tmp = bind_rows(lapply(names(plot2), \(x) tibble::tibble(
  variable = x,
  value = as.vector(plot2[[x]]),
  boot = as.vector(row(plot2[[x]])),
  step = as.vector(col(plot2[[x]]))
  )))

tmp %>% ggplot(aes(colour=variable, y=value, x=step)) +
  geom_line()

tmp %>% ggplot(aes(colour=variable, y=value, x=step)) +
  geom_line()+coord_cartesian(xlim=c(0,50))


```

```{r}
stoch = function(state, params, ...) {
  
  with(as.list(c(state, params)), {
    
    
    # max_p_virion_removal - max rate removal by fully actvated immune system
    p_virion_removal = max_p_virion_removal * immune_active/k_immune
    virions_removed = rbinom(1, virions, p_virion_removal)
    # virion_replication_rate - rate production removal by fully activated immune system
    virions_added = rpois(1, virion_replication_rate * target_producing)
    
    
    
    # max_p_infection - probability 1 virion will infect cell in fully susceptible target
    # should be possible if virions >> target for this to saturate.
    # this does not do so in a logit style fashion though because of the 
    # exponential growth of virions. It should be possible for complete runaway.
    # the balance between max_p_infection*
    
    #TODO: this could be a Beta?
    p_infection = max_p_infection*target_susceptible/k_target
    target_infected = rbinom(1, virions-virions_removed, p_infection)
    # you can't infect more that there are susceptible,
    target_infected = min(c(target_infected,target_susceptible))
    # this is infected targets but also the number of virions removed
    
    virions_1 = max(c(0,virions-virions_removed+virions_added-target_infected))
    
    # Target cells
    
    target_remaining = target_susceptible + target_exposed + target_producing
    target_removed = k_target - target_remaining
    target_recovered = rbinom(1, target_removed, p_target_recovery)
    
    
    target_susceptible_1 = 
      min(c(k_target,
        max(c(0,
              target_susceptible-target_infected+target_recovered
        ))
      ))
    
    
    target_start_producing = rbinom(1, target_exposed, p_producing_given_exposed)
    p_cellular_removal = max_p_cellular_removal * immune_active/k_immune
    target_exposed_removed = rbinom(1, target_exposed, p_cellular_removal)
    
    target_exposed_1 = 
      min(c(k_target,
        max(c(0,
              target_exposed - target_start_producing - target_exposed_removed + target_infected
        ))
      ))
     
    target_producing_removed = rbinom(1, target_producing, p_cellular_removal)
    #target_producing_death = rbinom(1, target_producing, p_producing_death)
    
    # NK 
    p_target_nk_elimiation = max_p_nk_elimination * target_producing / target_remaining
    target_nk_elimiation = rbinom(1, k_nk, p_target_nk_elimiation)
    
    #target_producing_death = min(target_producing,k_nk)
    
    target_producing_1 = 
      min(c(k_target,
        max(c(0,
              target_producing - target_producing_removed + 
                target_start_producing - #target_producing_death
                target_nk_elimiation
        ))
      ))

    # Immunity
    # At the moment immunity is modelled with one active immune type
    # that performs cellular and humoural adaptive immunity
    # plus a innate immunity in terms of NK cells. 
    # NK cells remove things very quickly
    # but saturate early.
    
    immune_dormant = k_immune - immune_priming - immune_active
    # immune_dormant = k_immune - immune_active
    
    p_immune_induced = max_p_immune_induced * target_producing / target_remaining
    # immune_start_active = rbinom(1, immune_dormant, p_immune_induced)
    
    immune_induced = rbinom(1, immune_dormant, p_immune_induced)
    immune_start_active = rbinom(1, immune_priming, p_active_given_priming)

    immune_priming_1 =
      min(c(k_immune,
        max(c(0,
              immune_priming + immune_induced - immune_start_active
        ))
      ))
      
    immune_senescence = rbinom(1, immune_active, p_senescence_given_active)
    
    immune_active_1 = 
      min(c(k_immune,
        max(c(0,
              immune_active + immune_start_active - immune_senescence
        ))
      ))
      
    return(list(virions = virions_1,
                  target_susceptible = target_susceptible_1,
                  target_exposed = target_exposed_1,
                  target_producing = target_producing_1,
                  immune_priming = immune_priming_1,
                  immune_active = immune_active_1))
  })
}


```

```{r}



params = tibble::tibble(
  
  # controls rate of falling and probability of entering chronic infection state, and final height of chronichly infected cells
  immune_strength = 0.9,
  k_target = 10000,
  k_immune = 10000,
  k_nk = 1000,
  
  viral_r0 = 0.8,
  viral_aggression = 0.25,
  
  max_p_virion_removal = immune_strength, # max probability a virion will be neuratlised given full immune activation
  
  # size of peak, size of steady state
  virion_replication_rate = 1+viral_r0, # rate at which infected cell produces new virions
  # will interact with lifespan of producing cell.
  # i.e. virion_replication_rate / p_producing_death > 1 for expansion in immune naive host
  # maybe can work out boundary for a given state of immunity.
  
  # faster and higher peak virions
  max_p_infection = 1/(1+viral_r0*viral_aggression), # probability a virion will infect a cell given fully susceptible targets
  p_producing_given_exposed = viral_aggression, # probability exposed cell transitions to producing
  
  p_target_recovery = 0.1, # probability a died cell is regenerated
  
  # Smaller values lead to higher risk of chronic infection:
  # needs to be larger that max_p_infection to get to elimination?
  max_p_cellular_removal = immune_strength, # max probabality infected cell removed given full immune activation
  max_p_nk_elimination = immune_strength,
  
  # p_producing_death = 0.4, # probability of spontaneous death of infected target - innate immunity
  
  max_p_immune_induced = 1, # maximum probability of activating an immune cell given all targets producing virus
  p_active_given_priming = 0.1, # 1/delay to immune activation
  
  p_senescence_given_active = 1/200, # 1/immune waning
  
  initial_virions = 0,
  initial_target_susceptible = k_target,
  initial_target_exposed = 0,
  initial_target_producing = 0,
  initial_immune_priming = 0,
  initial_immune_active = 0
)
```

```{r}



vary = c(0.1,0.3,0.5,0.7,0.9)

combined = tibble::tibble()

for (p in vary) {
  
  state = list(
    virions = 0,
    target_susceptible = k_target,
    target_exposed = 0,
    target_producing = 0,
    immune_priming = 0,
    immune_active = 0
  )
  
  out = tibble::as_tibble(state)
  params$p_active_given_priming = p
  
  for (i in 0:1000) {
    # if (i %in% c(0,21,70)) state$immune_priming = state$immune_priming + 20000
    if (i %% 100==50) state$virions = state$virions + 100
    # if (i==200) state$virions = state$virions + 100
    state = stoch(state, params)
    out = dplyr::bind_rows(out,tibble::as_tibble(state))
  }
  
  combined = combined %>% bind_rows(out %>% mutate(vary = p, time = row_number()))
}

combined %>% mutate(symptoms = 1-(target_susceptible+target_exposed+target_producing)/k_target) %>% pivot_longer(-c(time,vary)) %>% ggplot(aes(x=time,y=value, colour=as.factor(vary)))+geom_line()+
  coord_cartesian(ylim=c(0,NA))+
  facet_wrap(~name, scales = "free_y")


combined %>% pivot_longer(-c(time,vary)) %>% ggplot(aes(x=time,y=value, colour=as.factor(vary)))+geom_line()+
  coord_cartesian(ylim=c(0,NA), xlim=c(45,50+45))+
  facet_wrap(~name, scales = "free_y")

```