package io.github.ai4ci.abm;

import org.mapstruct.Mapper;
import org.mapstruct.Mapping;
import org.mapstruct.NullValueCheckStrategy;
import org.mapstruct.NullValuePropertyMappingStrategy;
import org.mapstruct.factory.Mappers;

/**
 * Generated mapping from current state to history entries. This copies
 * information that is needed for any stateful inspection of the model such as
 * changes in infection state. It is used in the update cycle to move a
 * PersonState to a PersonHistory (and equivalent for Outbreak). The
 * implementation is generated by MapStruct
 */
@Mapper(
		nullValueCheckStrategy = NullValueCheckStrategy.ALWAYS,
		nullValuePropertyMappingStrategy = NullValuePropertyMappingStrategy.IGNORE
)
public abstract class HistoryMapper {

	// N.B. must be in same directory as data otherwise generated code
	// does not import properly

	/**
	 * The Mapper instance, used to call the mapping functions. This is generated
	 * by MapStruct and should not be modified.
	 */
	public static HistoryMapper MAPPER = Mappers.getMapper(HistoryMapper.class);

	/**
	 * Creates a new OutbreakHistory entry from the current OutbreakState. This
	 * is called during the update cycle to record the state of the outbreak
	 * before any changes are made. The mapping is generated by MapStruct and
	 * should not be modified, but can be customized with additional @Mapping
	 * annotations if needed.
	 *
	 * @param currentState the current state of the outbreak to be recorded in
	 *                     history
	 * @return a new OutbreakHistory instance containing the relevant information
	 *         from the current state
	 */
	public abstract OutbreakHistory createHistory(OutbreakState currentState);

	/**
	 * Creates a new PersonHistory entry from the current PersonState. This is
	 * called during the update cycle to record the state of the person before
	 * any changes are made. The mapping is generated by MapStruct and should not
	 * be modified, but can be customized with additional @Mapping annotations if
	 * needed.
	 *
	 * @param currentState the current state of the person to be recorded in
	 *                     history
	 * @return a new PersonHistory instance containing the relevant information
	 *         from the current state
	 */
	@Mapping(
			target = "todaysContacts",
			expression = "java(new Contact[0])"
	)
	@Mapping(
			target = "todaysExposures",
			expression = "java(new Exposure[0])"
	)
	@Mapping(
			target = "todaysTests",
			expression = "java(new java.util.ArrayList<>())"
	)
	public abstract PersonHistory createHistory(PersonState currentState);

//	public Integer personStateId( PersonState source ) {
//		return source.getEntity().getId();
//	};

}