# Generated by InterfacerSchemaGenerator
# Do not edit manually

# maps to Java interface io.github.ai4ci.config.geography.MSOA
i_msoa <- interfacer::iface(
  name = character + not_missing ~ "maps to java field MSOA.setName",
  id = character + unique_id + not_missing ~ "maps to java field MSOA.setId"
)

