# Generated by InterfacerSchemaGenerator
# Do not edit manually

# maps to Java interface io.github.ai4ci.config.refdata.UKCensus$AgeGender
i_agegender <- interfacer::iface(
  gender = character + not_missing ~ "maps to java field AgeGender.gender",
  age = double + not_missing ~ "maps to java field AgeGender.age",
  geography = integer + not_missing ~ "maps to java field AgeGender.geography",
  index = character + not_missing ~ "maps to java field AgeGender.index",
  count = integer + not_missing ~ "maps to java field AgeGender.count",
  id = character + not_missing ~ "maps to java field AgeGender.id",
  total = integer + not_missing ~ "maps to java field AgeGender.total"
)

# maps to Java interface io.github.ai4ci.config.refdata.UKCensus$Commuting
i_commuting <- interfacer::iface(
  geography = integer + not_missing ~ "maps to java field Commuting.geography",
  commutingType = character + not_missing ~ "maps to java field Commuting.commutingType",
  index = character + not_missing ~ "maps to java field Commuting.index",
  count = integer + not_missing ~ "maps to java field Commuting.count",
  id = character + not_missing ~ "maps to java field Commuting.id",
  total = integer + not_missing ~ "maps to java field Commuting.total"
)

# maps to Java interface io.github.ai4ci.config.refdata.UKCensus$Distances
i_distances <- interfacer::iface(
  sourceGeography = integer + not_missing ~ "maps to java field Distances.sourceGeography",
  targetGeography = integer + not_missing ~ "maps to java field Distances.targetGeography",
  index = character + not_missing ~ "maps to java field Distances.index",
  id = character + not_missing ~ "maps to java field Distances.id",
  distance = double + not_missing ~ "maps to java field Distances.distance"
)

# maps to Java interface io.github.ai4ci.config.refdata.UKCensus$Ethnicity
i_ethnicity <- interfacer::iface(
  geography = integer + not_missing ~ "maps to java field Ethnicity.geography",
  subgroup = character + not_missing ~ "maps to java field Ethnicity.subgroup",
  index = character + not_missing ~ "maps to java field Ethnicity.index",
  group = character + not_missing ~ "maps to java field Ethnicity.group",
  count = integer + not_missing ~ "maps to java field Ethnicity.count",
  id = character + not_missing ~ "maps to java field Ethnicity.id",
  total = integer + not_missing ~ "maps to java field Ethnicity.total"
)

# maps to Java interface io.github.ai4ci.config.refdata.UKCensus$Geography
i_geography <- interfacer::iface(
  index = character + not_missing ~ "maps to java field Geography.index",
  name = character + not_missing ~ "maps to java field Geography.name",
  id = character + not_missing ~ "maps to java field Geography.id"
)

# maps to Java interface io.github.ai4ci.config.refdata.UKCensus$Industry
i_industry <- interfacer::iface(
  geography = integer + not_missing ~ "maps to java field Industry.geography",
  industryName = character + not_missing ~ "maps to java field Industry.industryName",
  index = character + not_missing ~ "maps to java field Industry.index",
  count = integer + not_missing ~ "maps to java field Industry.count",
  id = character + not_missing ~ "maps to java field Industry.id",
  total = integer + not_missing ~ "maps to java field Industry.total"
)

# maps to Java interface io.github.ai4ci.config.refdata.UKCensus$Unemployment
i_unemployment <- interfacer::iface(
  geography = integer + not_missing ~ "maps to java field Unemployment.geography",
  employmentType = character + not_missing ~ "maps to java field Unemployment.employmentType",
  fullTime = character + not_missing ~ "maps to java field Unemployment.fullTime",
  student = character + not_missing ~ "maps to java field Unemployment.student",
  employment = character + not_missing ~ "maps to java field Unemployment.employment",
  index = character + not_missing ~ "maps to java field Unemployment.index",
  count = integer + not_missing ~ "maps to java field Unemployment.count",
  id = character + not_missing ~ "maps to java field Unemployment.id",
  total = integer + not_missing ~ "maps to java field Unemployment.total"
)

