package io.github.ai4ci.functions;

import org.immutables.value.Value;

import com.fasterxml.jackson.annotation.JsonTypeInfo;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;

/**
 * Gaussian kernel function.
 *
 * <p>
 * This interface describes a simple Gaussian kernel function with parameters
 * for the mean and standard deviation. It is used as a simple example of a
 * kernel function and is not currently used in the model. Implementations are
 * generated by Immutables (see {@link ImmutableGaussianKernel}).
 *
 * @author Rob Challen
 */
@Value.Immutable
@JsonSerialize(as = ImmutableGaussianKernel.class)
@JsonDeserialize(as = ImmutableGaussianKernel.class)
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME)
@JsonTypeName("gaussian")
public interface GaussianKernel extends java.io.Serializable, KernelFunction {

	/**
	 * Mean of the Gaussian kernel.
	 *
	 * @return mean
	 */
	double getMu();

	/**
	 * Standard deviation of the Gaussian kernel.
	 *
	 * @return standard deviation
	 */
	double getSigma();

	/**
	 * Compute the raw value of the Gaussian kernel at a given point.
	 *
	 * <p>
	 * The raw value is computed using the formula:
	 *
	 * <pre>
	 * K(t) = exp(-((t - mu) ^ 2) / (2 * sigma ^ 2))
	 * </pre>
	 *
	 * @param t input value
	 * @return raw kernel value at t
	 */
	@Override
	default double rawValue(int t) {
		var deltat = this.getMu() - t;
		return Math
			.exp(-((deltat * deltat) / (2 * this.getSigma() * this.getSigma())));
	}

}
